### ISSUE TITLE
instalar glpi 

### ISSUE THREAD

**Issue by giovanni-morato** [DanielStatera/rep-tools#12]

**Comment by DanielStatera** [comment]
Script de instalação criado "tool_installation.ps1". Nele temos a instalação de forma separada do Tactical, Acronis, GLPI e FAQ ou a instalação conjunta da ferramentas.
OBS: O código ps1 aqui no github não contem a url correta nem o auth correto do tactical par instalação. O arquivo a ser usado para instalação das ferramentas está no sharepoint
